import {test,expect} from '@playwright/test';
const token=process.env.MRKT_BROWSER_TOKEN,base=process.env.MRKT_BROWSER_URL||'http://127.0.0.1:8080';
const noOverflow=async page=>expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBeTruthy();
const contrast=async page=>page.evaluate(()=>{const lum=s=>{let n=s.match(/-?[\d.]+/g).map(Number),r,g,b;if(s.startsWith('okl')){let L=n[0],a,q;if(L>1)L/=100;if(s.startsWith('oklch')){const C=n[1],h=n[2]*Math.PI/180;a=C*Math.cos(h);q=C*Math.sin(h)}else{a=n[1];q=n[2]}const l=(L+.3963377774*a+.2158037573*q)**3,m=(L-.1055613458*a-.0638541728*q)**3,x=(L-.0894841775*a-1.291485548*q)**3;r=4.0767416621*l-3.3077115913*m+.2309699292*x;g=-1.2684380046*l+2.6097574011*m-.3413193965*x;b=-.0041960863*l-.7034186147*m+1.707614701*x}else{[r,g,b]=n.slice(0,3).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4})}return.2126*r+.7152*g+.0722*b},ratio=(a,b)=>{a=lum(a);b=lum(b);return(Math.max(a,b)+.05)/(Math.min(a,b)+.05)},body=getComputedStyle(document.body),brand=getComputedStyle(document.querySelector('.brand')),button=getComputedStyle(document.querySelector('button'));return{body:ratio(body.color,body.backgroundColor),icon:ratio(brand.color,body.backgroundColor),focus:ratio(button.outlineColor,body.backgroundColor)}});
for(const width of [320,375,414,768,1280])test(`operational UI at ${width}px`,async({page})=>{
 test.skip(!token,'MRKT_BROWSER_TOKEN required');await page.setViewportSize({width,height:800});await page.goto(base+'/login');await page.getByLabel('API token').fill(token);await page.getByRole('button',{name:'Sign in'}).click();await expect(page.locator('#main')).toBeVisible();await noOverflow(page);
 for(const scheme of ['light','dark']){await page.emulateMedia({colorScheme:scheme});const c=await contrast(page);expect(c.body).toBeGreaterThanOrEqual(4.5);expect(c.icon).toBeGreaterThanOrEqual(3);expect(c.focus).toBeGreaterThanOrEqual(3)}await page.emulateMedia({colorScheme:'light'});
 await page.keyboard.press('Control+k');await expect(page.locator('#view-search')).toBeVisible();await expect(page.locator('#view-query')).toBeFocused();await page.locator('#view-query').fill('release');await expect(page.locator('#view-results a:visible')).toHaveCount(1);await page.locator('#view-search').getByRole('button',{name:'Close'}).click();await expect(page.locator('#view-search')).not.toBeVisible();
 const nav=name=>page.getByRole('navigation',{name:'Project navigation'}).getByRole('link',{name});await page.screenshot({path:`assets/brand/screenshots/overview-${width}.png`,fullPage:true});for(const view of ['Contacts','Releases']){await nav(view).click();await noOverflow(page);await page.screenshot({path:`assets/brand/screenshots/${view.toLowerCase()}-${width}.png`,fullPage:true})}
 if(width===1280){await page.getByRole('link',{name:'Details'}).first().click();await expect(page.getByText('Comparison with active release')).toBeVisible();await page.getByLabel('Locale').selectOption('it');await page.getByRole('button',{name:'Update preview'}).click();await expect(page.getByText('/ it',{exact:false})).toBeVisible();await expect(page.getByTitle('Sandboxed message preview').contentFrame().locator('body')).not.toBeEmpty();await page.getByRole('button',{name:'Show or hide manifest'}).click();await expect(page.locator('#release-manifest')).toBeVisible();await nav('Deliveries').click();await page.getByRole('link',{name:'Details'}).first().click();await expect(page.getByTitle('Sandboxed delivered message').contentFrame().locator('body')).not.toBeEmpty();await nav('Sequences').click();await page.getByRole('link',{name:'Details'}).first().click();await expect(page.getByText('Why:',{exact:false})).toBeVisible()}
 await nav('Backup & recovery').click();await expect(page.getByRole('heading',{name:'Recovery requires reconciliation'})).toBeVisible();await noOverflow(page);await page.goto(base+'/does-not-exist');await expect(page.locator('body')).toContainText('404');
});
