#!/usr/bin/env node
import {spawn,spawnSync} from 'node:child_process';
import {mkdtempSync,rmSync,readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import net from 'node:net';

const root=resolve(import.meta.dirname,'..');const temp=mkdtempSync(join(tmpdir(),'mrkt-acceptance-'));const bin=join(temp,'mrkt');const project=join(temp,'project');
const token='acceptance-admin-token-0000000000000000';const recipient=`acceptance-${Date.now()}@example.test`;let server;let logs='';
const port=await new Promise((ok,no)=>{const s=net.createServer();s.on('error',no);s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>ok(p))})});const base=`http://127.0.0.1:${port}`;
const env={...process.env,MRKT_DEVELOPMENT:'true',MRKT_CHALLENGE_BYPASS:'true',MRKT_PUBLIC_URL:base,MRKT_LISTEN:`127.0.0.1:${port}`,MRKT_DB_PATH:join(temp,'mrkt.db'),MRKT_ENCRYPTION_KEY:'base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',MRKT_ADMIN_TOKEN:token,MRKT_S3_BUCKET:'mrkt',MRKT_S3_REGION:'us-east-1',MRKT_S3_ENDPOINT:'http://127.0.0.1:9000',MRKT_S3_PATH_STYLE:'true',AWS_ACCESS_KEY_ID:'mrktdev',AWS_SECRET_ACCESS_KEY:'mrktdev-secret',MRKT_SMTP_HOST:'127.0.0.1',MRKT_SMTP_PORT:'1025',MRKT_SMTP_TLS_MODE:'plain',MRKT_URL:base,MRKT_TOKEN:token};
function run(args,input=''){const r=spawnSync(bin,args,{cwd:root,env,input,encoding:'utf8'});if(r.status!==0)throw new Error(`${args.join(' ')} failed\n${r.stdout}${r.stderr}`);return r.stdout}
async function request(path,{method='GET',body,auth=true,headers={}}={}){const r=await fetch(base+path,{method,headers:{...(auth?{authorization:`Bearer ${token}`}:{ }),...(body?{'content-type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined});const text=await r.text();if(!r.ok)throw new Error(`${method} ${path}: ${r.status} ${text}`);try{return JSON.parse(text)}catch{return text}}
async function waitFor(fn,label,ms=12000){const until=Date.now()+ms;let last;while(Date.now()<until){try{const v=await fn();if(v)return v}catch(e){last=e}await new Promise(r=>setTimeout(r,300))}throw new Error(`timeout waiting for ${label}${last?`: ${last}`:''}`)}
try{
 let r=spawnSync('go',['build','-o',bin,'./cmd/mrkt'],{cwd:root,encoding:'utf8'});if(r.status!==0)throw new Error(r.stderr);
 for(const preset of ['coming-soon','welcome','newsletter','launch'])for(const brand of ['flowrent','cheerful','mimux','humux']){const d=join(temp,'matrix',preset,brand);run(['init','--preset',preset,'--dir',d]);const p=join(d,'mrkt.yaml');writeFileSync(p,readFileSync(p,'utf8').replace(`name: ${preset}`,`name: ${brand}`),{mode:0o600});run(['validate','--dir',d])}
 r=spawnSync('go',['test','./internal/mcpserver'],{cwd:root,encoding:'utf8'});if(r.status!==0)throw new Error(`MCP schema/annotation tests failed\n${r.stdout}${r.stderr}`);
 run(['server','init']);server=spawn(bin,['server'],{cwd:root,env,stdio:['ignore','pipe','pipe']});server.stderr.on('data',b=>logs+=b);
 await waitFor(async()=>{try{return (await fetch(base+'/healthz')).ok}catch{return false}},'server health');
 run(['init','--preset','welcome','--dir',project]);const manifestPath=join(project,'mrkt.yaml');let yaml=readFileSync(manifestPath,'utf8');yaml=yaml.replace('      - {id: send, type: send, message: welcome, next: done}\n      - {id: done, type: complete}','      - {id: send, type: send, message: welcome, next: wait}\n      - {id: wait, type: delay, delay: 2s, next: followup}\n      - {id: followup, type: send, message: welcome, next: done}\n      - {id: done, type: complete}');writeFileSync(manifestPath,yaml,{mode:0o600});run(['projects','create'],JSON.stringify({id:'welcome',name:'Welcome acceptance'}));run(['deploy','--dir',project]);
 run(['api','releases','--project','welcome','--id','_','simulate'],JSON.stringify({sequence:'welcome',variables:{Name:'Simulation',Email:'simulation@example.test',Locale:'it'},start:new Date().toISOString()}));
 await request('/public/welcome/subscribe',{method:'POST',auth:false,body:{email:recipient,name:'Acceptance',list:'newsletter',source:'acceptance',challenge_token:'development'}});
 async function messagesForRecipient(){const list=await (await fetch('http://127.0.0.1:8025/api/v1/messages')).json();const found=[];for(const m of list.messages||[]){const d=await (await fetch(`http://127.0.0.1:8025/api/v1/message/${m.ID}`)).json();if(JSON.stringify(d).includes(recipient))found.push(d)}return found}
 const captured=await waitFor(async()=>{const xs=await messagesForRecipient();return xs.find(x=>JSON.stringify(x).includes('/confirm?token='))},'confirmation email');
 const raw=JSON.stringify(captured);const match=raw.match(new RegExp(`${base.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}/public/welcome/confirm\\?token=([^"\\s<>\\\\]+)`));if(!match)throw new Error('confirmation URL not found in capture');
 await request('/public/welcome/confirm',{method:'POST',auth:false,body:{token:decodeURIComponent(match[1])}});const welcome=await waitFor(async()=>{const xs=await messagesForRecipient();return xs.find(x=>JSON.stringify(x).includes('/unsubscribe?token='))},'welcome email');const before=(await messagesForRecipient()).length;
 const unsubRaw=JSON.stringify(welcome);const unsub=unsubRaw.match(new RegExp(`${base.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}/public/welcome/unsubscribe\\?token=([^"\\s<>\\\\]+)`));if(!unsub)throw new Error('unsubscribe URL not found in welcome capture');await request(`/public/welcome/unsubscribe?token=${decodeURIComponent(unsub[1])}`,{method:'POST',auth:false,body:{'List-Unsubscribe':'One-Click'}});
 const event={key:'duplicate-article-1',type:'article.published',payload:{title:'Synthetic'}};await request('/api/v1/projects/welcome/events',{method:'POST',body:event,headers:{'idempotency-key':'duplicate-event-1'}});await request('/api/v1/projects/welcome/events',{method:'POST',body:event,headers:{'idempotency-key':'duplicate-event-1'}});
 await new Promise(r=>setTimeout(r,5500));const final=(await messagesForRecipient()).length;if(final!==before)throw new Error('message sent after unsubscribe');
 mkdirSync(join(root,'assets','brand','screenshots'),{recursive:true});const browser=spawnSync('npx',['playwright','test'],{cwd:root,env:{...process.env,MRKT_BROWSER_URL:base,MRKT_BROWSER_TOKEN:token},encoding:'utf8',timeout:240000});if(browser.status!==0)throw new Error(`browser checks failed\n${browser.stdout}${browser.stderr}`);
 console.log(JSON.stringify({ok:true,base,confirmation:true,welcome:true,unsubscribe_blocked:true,duplicate_event_replay:true,browser_cases:5},null,2));
}catch(e){console.error(e.stack||e);if(logs)console.error('server diagnostics:\n'+logs);process.exitCode=1}finally{if(server&&!server.killed){server.kill('SIGTERM')}if(server?.exitCode===null){await new Promise(r=>server.once('exit',r))}rmSync(temp,{recursive:true,force:true})}
