import {execFileSync} from 'node:child_process';
import {mkdir,readdir,readFile,writeFile,copyFile,chmod} from 'node:fs/promises';
const modules=execFileSync('go',['list','-m','-f','{{.Path}}\t{{.Version}}\t{{.Dir}}','all'],{encoding:'utf8'}).trim().split('\n').slice(1).map(l=>l.split('\t'));
const packages=JSON.parse(await readFile('package.json','utf8')).devDependencies;
const notices=['# Third-party notices','', 'mrkt is MIT licensed. The following maintained dependencies retain their own licenses. Full upstream notices are copied into licenses/. Runtime Go dependencies are pinned in go.mod/go.sum; browser and build dependencies are pinned in package-lock.json.',''];
await mkdir('licenses',{recursive:true});
async function add(name,version,dir){if(!dir)return;const target='licenses/'+name.replaceAll('/','_');await mkdir(target,{recursive:true});const files=(await readdir(dir)).filter(n=>/^(licen[sc]e|copying|notice|ofl)(\.|$)/i.test(n));for(const file of files){try{await chmod(target+'/'+file,0o644).catch(e=>{if(e.code!=='ENOENT')throw e});await copyFile(dir+'/'+file,target+'/'+file);await chmod(target+'/'+file,0o644)}catch(err){if(err.code!=='EISDIR')throw err}}notices.push(`- ${name} ${version}: ${files.length?'[upstream license](licenses/'+name.replaceAll('/','_')+'/'+files[0]+')':'see upstream module license'}`)}
for(const [name,version,dir]of modules)await add(name,version,dir);
for(const [name,version]of Object.entries(packages))await add(name,version,'node_modules/'+name);
notices.push('','Development container services are separate programs: MinIO is AGPL-3.0, Mailpit is MIT, and Litestream is Apache-2.0. mrkt uses their network/replication interfaces; their source is not incorporated into the application. Obtain their corresponding source and image notices from their upstream repositories when redistributing those services. SQLite itself is public domain; modernc’s Go driver and translated support packages retain their included licenses.','', 'Original mrkt wordmark/icon vector paths are MIT. Fontsource Space Grotesk and Inter font files are SIL OFL 1.1 and are distributed with their upstream notices. The generated message-sequence illustration uses no third-party reference asset.');
await writeFile('THIRD_PARTY_NOTICES.md',notices.join('\n')+'\n');
